name: Test

on:
  push:
    branches: [ "**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GOPATH: "${{ github.workspace }}/.go"
  GOVERSION: "1.17.x"

jobs:
  lint:
    name: Go lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GOVERSION }}"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: "v1.62"

  test:
    name: Go test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GOVERSION }}"

      - name: Run go tests
        run: |
          go test -v \
            -race \
            -cover \
            -covermode=atomic \
            ./...

  results:
    if: always()
    runs-on: ubuntu-24.04
    name: Test Results
    needs:
    - lint
    - test
    steps:
    - run: exit 1
      if: |
        contains(needs.*.result, 'failure') ||
          contains(needs.*.result, 'cancelled')
